window.bingoProductCatalog = [
  {
    code: "BT-SJ-001",
    category: "single-jersey",
    series: "Single Jersey",
    name: "New Trend Cotton",
    composition: "96% cotton, 4% spandex",
    width: "117cm -0/+5",
    gsm: "320gsm +/-5%",
    season: "Summer",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sj-001.jpg"
  },
  {
    code: "BT-SJ-002",
    category: "single-jersey",
    series: "Single Jersey",
    name: "Carrera Cotton",
    composition: "92.5% cotton, 7.5% spandex",
    width: "169cm -0/+5",
    gsm: "199gsm +/-5%",
    season: "Summer",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sj-002.jpg"
  },
  {
    code: "BT-SJ-003",
    category: "single-jersey",
    series: "Single Jersey",
    name: "32S Snow-Wash Double-Yarn Jersey",
    composition: "100% cotton",
    width: "174cm -0/+5",
    gsm: "255gsm +/-5%",
    season: "Summer",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-sj-003.jpg"
  },
  {
    code: "BT-SJ-004",
    category: "single-jersey",
    series: "Single Jersey",
    name: "Snow-Wash Original Cotton",
    composition: "100% cotton",
    width: "182cm -0/+5",
    gsm: "294gsm +/-5%",
    season: "Summer",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-sj-004.jpg"
  },
  {
    code: "BT-SJ-005",
    category: "single-jersey",
    series: "Single Jersey",
    name: "40S/1 Compact Cotton Double-Yarn Jersey",
    composition: "100% cotton",
    width: "175cm -0/+5",
    gsm: "244gsm +/-5%",
    season: "Summer",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sj-005.jpg"
  },
  {
    code: "BT-SJ-006",
    category: "single-jersey",
    series: "Single Jersey",
    name: "New Cool Cotton",
    composition: "92% cotton, 8% spandex",
    width: "176cm -0/+5",
    gsm: "188gsm +/-5%",
    season: "Summer",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sj-006.jpg"
  },
  {
    code: "BT-SW-001",
    category: "sweatshirt",
    series: "Sweatshirt",
    name: "Chinese Streetwear Fleece",
    composition: "100% cotton",
    width: "178cm -0/+5",
    gsm: "471gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-sw-001.jpg"
  },
  {
    code: "BT-SW-002",
    category: "sweatshirt",
    series: "Sweatshirt",
    name: "Dynamic Paris Twill",
    composition: "58.5% cotton, 41.5% polyester",
    width: "174cm -0/+5",
    gsm: "294gsm +/-5%",
    season: "Spring/Fall",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sw-002.jpg"
  },
  {
    code: "BT-SW-003",
    category: "sweatshirt",
    series: "Sweatshirt",
    name: "New Diamond Texture",
    composition: "70.95% cotton, 29.05% polyester",
    width: "174cm -0/+5",
    gsm: "366gsm +/-5%",
    season: "Spring/Fall",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-sw-003.jpg"
  },
  {
    code: "BT-SW-004",
    category: "sweatshirt",
    series: "Sweatshirt",
    name: "Paris Twill",
    composition: "92.3% cotton, 7.7% polyester",
    width: "175cm -0/+5",
    gsm: "427gsm +/-5%",
    season: "Spring/Fall",
    application: "Premium men's styles",
    image: "./assets/products/catalog/bt-sw-004.jpg"
  },
  {
    code: "BT-SW-005",
    category: "sweatshirt",
    series: "Sweatshirt",
    name: "New Geometric Double Knit",
    composition: "75.35% cotton, 17.15% polyester, 7.5% spandex",
    width: "164cm -0/+5",
    gsm: "277gsm +/-5%",
    season: "Spring/Fall",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-sw-005.jpg"
  },
  {
    code: "BT-DK-001",
    category: "double-knit",
    series: "Double Knit",
    name: "New Structured Rib",
    composition: "80% cotton, 20% polyester",
    width: "175cm -0/+5",
    gsm: "316gsm +/-5%",
    season: "Spring/Fall",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-dk-001.jpg"
  },
  {
    code: "BT-DK-002",
    category: "double-knit",
    series: "Double Knit",
    name: "Washed AD Double Knit",
    composition: "80.85% cotton, 19.15% polyester",
    width: "173cm -0/+5",
    gsm: "446gsm +/-5%",
    season: "Winter",
    application: "Low-shrinkage after wash",
    image: "./assets/products/catalog/bt-dk-002.jpg"
  },
  {
    code: "BT-DK-003",
    category: "double-knit",
    series: "Double Knit",
    name: "AD Double Knit",
    composition: "80.85% cotton, 19.15% polyester",
    width: "171cm -0/+5",
    gsm: "449gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-dk-003.jpg"
  },
  {
    code: "BT-DK-004",
    category: "double-knit",
    series: "Double Knit",
    name: "Rosella Double Knit",
    composition: "100% cotton",
    width: "176cm -0/+5",
    gsm: "244gsm +/-5%",
    season: "Summer",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-dk-004.jpg"
  },
  {
    code: "BT-FT-001",
    category: "terry",
    series: "Terry",
    name: "Snow-Wash Maybach Terry",
    composition: "100% cotton",
    width: "171cm -0/+5",
    gsm: "421gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-ft-001.jpg"
  },
  {
    code: "BT-FT-002",
    category: "terry",
    series: "Terry",
    name: "Snow-Wash Chinese Streetwear Fleece",
    composition: "100% cotton",
    width: "178cm -0/+5",
    gsm: "471gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-ft-002.jpg"
  },
  {
    code: "BT-FT-003",
    category: "terry",
    series: "Terry",
    name: "New Maybach Terry",
    composition: "100% cotton",
    width: "171cm -0/+5",
    gsm: "421gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-ft-003.jpg"
  },
  {
    code: "BT-FT-004",
    category: "terry",
    series: "Terry",
    name: "New Macallan Sweatshirt Fleece",
    composition: "81.7% cotton, 18.3% polyester",
    width: "171cm -0/+5",
    gsm: "310gsm +/-5%",
    season: "Spring/Fall",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-ft-004.jpg"
  },
  {
    code: "BT-FT-005",
    category: "terry",
    series: "Terry",
    name: "Panamera Sweatshirt Fleece",
    composition: "100% cotton",
    width: "174cm -0/+5",
    gsm: "482gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-ft-005.jpg"
  },
  {
    code: "BT-FT-006",
    category: "terry",
    series: "Terry",
    name: "Chinese Streetwear Fleece",
    composition: "100% cotton",
    width: "178cm -0/+5",
    gsm: "471gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-ft-006.jpg"
  },
  {
    code: "BT-BF-001",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "New Precision Aohan Fleece",
    composition: "84.4% cotton, 15.6% polyester",
    width: "176cm -0/+5",
    gsm: "404gsm +/-5%",
    season: "Winter",
    application: "Women's and kids' fashion",
    image: "./assets/products/catalog/bt-bf-001.jpg"
  },
  {
    code: "BT-BF-002",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "Washed Aochuang Fleece",
    composition: "84.95% cotton, 15.05% polyester",
    width: "178cm -0/+5",
    gsm: "505gsm +/-5%",
    season: "Winter",
    application: "Low-shrinkage after wash",
    image: "./assets/products/catalog/bt-bf-002.jpg"
  },
  {
    code: "BT-BF-003",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "New Dense Fashion Fleece",
    composition: "49.45% cotton, 50.55% polyester",
    width: "171cm -0/+5",
    gsm: "454gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-bf-003.jpg"
  },
  {
    code: "BT-BF-004",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "New Expo Plush Fleece",
    composition: "42% cotton, 53% polyester, 5% other fiber",
    width: "176cm -0/+5",
    gsm: "382gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-bf-004.jpg"
  },
  {
    code: "BT-BF-005",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "New Simi Fleece",
    composition: "86.7% cotton, 13.3% polyester",
    width: "173cm -0/+5",
    gsm: "400gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-bf-005.jpg"
  },
  {
    code: "BT-BF-006",
    category: "brushed-fleece",
    series: "Brushed Fleece",
    name: "Milan Fashion Fleece",
    composition: "49% cotton, 51% polyester",
    width: "174cm -0/+5",
    gsm: "465gsm +/-5%",
    season: "Winter",
    application: "Unisex streetwear",
    image: "./assets/products/catalog/bt-bf-006.jpg"
  }
];
