window.bingoGarmentLaunchCodes = [
  "BG-GM-003",
  "BG-GM-006",
  "BG-GM-008",
  "BG-GM-009",
  "BG-GM-010",
  "BG-GM-011"
];

window.bingoGarmentCatalog = [
  {
    code: "BG-GM-001",
    name: "Relaxed Basketball Tank",
    priceCny: 52,
    unit: "piece",
    image: "./assets/garments/bg-gm-001.webp",
    category: "tops",
    categoryLabel: "Tanks",
    gsm: "190gsm",
    composition: "Cotton blend - exact ratio to confirm",
    fit: "Relaxed",
    sizes: "S-XXL",
    season: "Spring / Summer",
    description: "Sleeveless streetwear base for training-inspired and warm-weather capsules.",
    visual: "tank",
    tone: "mint"
  },
  {
    code: "BG-GM-002",
    name: "420gsm Washed Terry Shorts",
    priceCny: 86,
    unit: "piece",
    image: "./assets/garments/bg-gm-002.webp",
    category: "bottoms",
    categoryLabel: "Bottoms",
    gsm: "420gsm",
    composition: "100% cotton - bulk confirmation required",
    fit: "Relaxed",
    sizes: "S-XXL",
    season: "Spring / Summer",
    description: "Heavy loop-back shorts with a washed direction for premium streetwear sets.",
    visual: "shorts",
    tone: "rose"
  },
  {
    code: "BG-GM-003",
    name: "275gsm Earth-Tone Oversized Tee",
    priceCny: 61,
    unit: "piece",
    image: "./assets/garments/bg-gm-003.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "275gsm",
    composition: "100% cotton - bulk confirmation required",
    fit: "Oversized",
    sizes: "S-XXL",
    season: "Spring / Summer",
    description: "Heavy cotton jersey direction for muted color programs and relaxed silhouettes.",
    visual: "tee",
    tone: "gold"
  },
  {
    code: "BG-GM-004",
    name: "230gsm Double-Yarn Oversized Tee",
    priceCny: 58,
    unit: "piece",
    image: "./assets/garments/bg-gm-004.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "230gsm",
    composition: "100% cotton - bulk confirmation required",
    fit: "Oversized",
    sizes: "S-XXL",
    season: "Spring / Summer",
    description: "A substantial blank tee base for screen print, embroidery or private labels.",
    visual: "tee",
    tone: "sky"
  },
  {
    code: "BG-GM-005",
    name: "350gsm Fleece Hoodie Set",
    priceCny: 83,
    unit: "set",
    image: "./assets/garments/bg-gm-005.webp",
    category: "hoodies",
    categoryLabel: "Hoodies & sets",
    gsm: "350gsm",
    composition: "Cotton blend - full blend to confirm",
    fit: "Oversized",
    sizes: "S-XXL",
    season: "Autumn / Winter",
    description: "Pullover hoodie and sweatpants direction with a warm brushed interior.",
    visual: "set",
    tone: "lilac"
  },
  {
    code: "BG-GM-006",
    name: "275gsm Cotton Boxy Tee",
    priceCny: 59,
    unit: "piece",
    image: "./assets/garments/bg-gm-006.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "275gsm",
    composition: "100% cotton - bulk confirmation required",
    fit: "Boxy",
    sizes: "S-XXL",
    season: "Spring / Summer / Autumn",
    description: "Shorter, wider streetwear proportion for premium blank and graphic programs.",
    visual: "tee",
    tone: "mint"
  },
  {
    code: "BG-GM-007",
    name: "245gsm Technical-Finish Tee",
    priceCny: 57,
    unit: "piece",
    image: "./assets/garments/bg-gm-007.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "245gsm",
    composition: "Cotton blend - 71-80% cotton listed",
    fit: "Regular",
    sizes: "XS-XXL",
    season: "Spring / Summer / Autumn",
    description: "Performance-finish concept; all functional claims require test-report verification.",
    visual: "tee",
    tone: "sky"
  },
  {
    code: "BG-GM-008",
    name: "250gsm Vintage-Wash Oversized Tee",
    priceCny: 62,
    unit: "piece",
    image: "./assets/garments/bg-gm-008.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "250gsm",
    composition: "100% cotton - bulk confirmation required",
    fit: "Oversized",
    sizes: "S-XXL",
    season: "Spring / Summer / Autumn",
    description: "Washed cotton blank direction for vintage streetwear and tonal collections.",
    visual: "tee",
    tone: "rose"
  },
  {
    code: "BG-GM-009",
    name: "350gsm Fleece Zip Hoodie Set",
    priceCny: 83,
    unit: "set",
    image: "./assets/garments/bg-gm-009.webp",
    category: "hoodies",
    categoryLabel: "Hoodies & sets",
    gsm: "350gsm",
    composition: "Cotton blend - full blend to confirm",
    fit: "Oversized",
    sizes: "S-XXL",
    season: "Autumn / Winter",
    description: "Zip hoodie and sweatpants set for coordinated private-label drops.",
    visual: "set",
    tone: "gold"
  },
  {
    code: "BG-GM-010",
    name: "350gsm Fleece Straight-Leg Sweatpants",
    priceCny: 83,
    unit: "piece",
    image: "./assets/garments/bg-gm-010.webp",
    category: "bottoms",
    categoryLabel: "Bottoms",
    gsm: "350gsm",
    composition: "Cotton blend - full blend to confirm",
    fit: "Relaxed straight leg",
    sizes: "S-XXL",
    season: "Autumn / Winter",
    description: "Heavy casual sweatpants direction with a clean straight-leg silhouette.",
    visual: "pants",
    tone: "lilac"
  },
  {
    code: "BG-GM-011",
    name: "350gsm Fleece Oversized Hoodie",
    priceCny: 93,
    unit: "piece",
    image: "./assets/garments/bg-gm-011.webp",
    category: "hoodies",
    categoryLabel: "Hoodies & sets",
    gsm: "350gsm",
    composition: "To confirm before sampling",
    fit: "Oversized",
    sizes: "To confirm",
    season: "Autumn / Winter",
    description: "Warm pullover hoodie base for embroidery, print and custom trim development.",
    visual: "hoodie",
    tone: "mint"
  },
  {
    code: "BG-GM-012",
    name: "385gsm Heavyweight Relaxed Tee",
    priceCny: 75,
    unit: "piece",
    image: "./assets/garments/bg-gm-012.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "385gsm",
    composition: "To confirm before sampling",
    fit: "Relaxed",
    sizes: "To confirm",
    season: "Spring / Autumn",
    description: "Extra-heavy jersey direction for structured silhouettes and premium hand feel.",
    visual: "tee",
    tone: "rose"
  },
  {
    code: "BG-GM-013",
    name: "190gsm Cotton Oversized Basic Tee",
    priceCny: 52,
    unit: "piece",
    image: "./assets/garments/bg-gm-013.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "190gsm",
    composition: "Cotton - ratio to confirm",
    fit: "Oversized",
    sizes: "To confirm",
    season: "Spring / Summer",
    description: "Lighter blank tee direction for warm climates and entry-level sampling.",
    visual: "tee",
    tone: "sky"
  },
  {
    code: "BG-GM-014",
    name: "Slub Cotton Relaxed Tee",
    priceCny: 58,
    unit: "piece",
    image: "./assets/garments/bg-gm-014.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "To confirm",
    composition: "Slub cotton - exact blend to confirm",
    fit: "Relaxed",
    sizes: "To confirm",
    season: "Spring / Summer",
    description: "Textured slub-jersey concept for breathable, casual private-label collections.",
    visual: "tee",
    tone: "gold"
  },
  {
    code: "BG-GM-015",
    name: "Women's Slub Cotton Regular Tee",
    priceCny: 46,
    unit: "piece",
    image: "./assets/garments/bg-gm-015.webp",
    category: "womens",
    categoryLabel: "Women's tops",
    gsm: "To confirm",
    composition: "Slub cotton - exact blend to confirm",
    fit: "Regular",
    sizes: "To confirm",
    season: "Spring / Summer",
    description: "Clean shoulder line and everyday proportion for womenswear basics programs.",
    visual: "tee",
    tone: "rose"
  },
  {
    code: "BG-GM-016",
    name: "Lightweight Summer Performance Tee",
    priceCny: 55,
    unit: "piece",
    image: "./assets/garments/bg-gm-016.webp",
    category: "tops",
    categoryLabel: "Performance tops",
    gsm: "To confirm",
    composition: "To confirm before sampling",
    fit: "Regular",
    sizes: "To confirm",
    season: "Spring / Summer",
    description: "Lightweight technical concept; finish and protection claims require lab evidence.",
    visual: "tee",
    tone: "mint"
  },
  {
    code: "BG-GM-017",
    name: "305gsm Earth-Tone Oversized Tee",
    priceCny: 66,
    unit: "piece",
    image: "./assets/garments/bg-gm-017.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "305gsm",
    composition: "Cotton - ratio to confirm",
    fit: "Oversized",
    sizes: "To confirm",
    season: "Spring / Autumn",
    description: "Dense cotton jersey direction for structured blanks and muted color stories.",
    visual: "tee",
    tone: "gold"
  },
  {
    code: "BG-GM-018",
    name: "Women's 210gsm Cropped Tee",
    priceCny: 45,
    unit: "piece",
    image: "./assets/garments/bg-gm-018.webp",
    category: "womens",
    categoryLabel: "Women's tops",
    gsm: "210gsm",
    composition: "To confirm before sampling",
    fit: "Cropped fitted",
    sizes: "To confirm",
    season: "Spring / Summer",
    description: "Compact womenswear tee base for fitted streetwear and capsule collections.",
    visual: "tee",
    tone: "lilac"
  },
  {
    code: "BG-GM-019",
    name: "Snow-Wash Cropped Boxy Tee",
    priceCny: 65,
    unit: "piece",
    image: "./assets/garments/bg-gm-019.webp",
    category: "tees",
    categoryLabel: "T-shirts",
    gsm: "To confirm",
    composition: "To confirm before sampling",
    fit: "Cropped boxy",
    sizes: "To confirm",
    season: "Spring / Summer / Autumn",
    description: "Vintage snow-wash direction with a shorter, wider streetwear silhouette.",
    visual: "tee",
    tone: "sky"
  },
  {
    code: "BG-GM-020",
    name: "Cropped Fleece Zip Hoodie",
    priceCny: 112,
    unit: "piece",
    image: "./assets/garments/bg-gm-020.webp",
    category: "hoodies",
    categoryLabel: "Hoodies & sets",
    gsm: "To confirm",
    composition: "To confirm before sampling",
    fit: "Cropped oversized",
    sizes: "To confirm",
    season: "Autumn / Winter",
    description: "Short-body zip hoodie direction with dropped shoulders and warm fleece.",
    visual: "hoodie",
    tone: "rose"
  }
];
